enquete/enquete/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

enquete/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('comments/<int:pk>', views.CommentView.as_view(), name='comment'),
    path('<int:question_id>/vote', views.vote, name='vote'),
]

enquete/main/models.py
from django.db import models
from django.utils import timezone
import datetime



# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Data de publicação')

    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now-datetime.timedelta(days=1)<=self.pub_date<=now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Publicada recentemente'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Comment(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    pub_date = models.DateTimeField('Data de publicação')
    comment_autor = models.CharField(max_length=200)
    comment_text = models.TextField()

    def __str__(self):
        return self.comment_text
    

enquete/main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice, Comment

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'main/index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
            ).order_by('-pub_date')[:5]
    

class DetailView(generic.DetailView):
    model = Question
    template_name = 'main/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte = timezone.now())
    
class CommentView(generic.DetailView):
    model = Comment
    template_name = 'main/comment.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'main/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'main/detail.html', {
            'question':question,
            'error_message':"Opção não selecionada.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('main:results',
        args=(question_id,)))

enquete/main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'main:index' %}">Enquete</a>
        </div>
    </nav>
    {% block data_block %} {% endblock %}
</body>

</html>

enquete/main/templates/main/comment.html
{% extends 'main/base.html'%} {% block data_block %}
<div class="container">
    <div class="card w-100 mt-3" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ comment.comment_autor }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ comment.pub_date }}</h6>
            <p class="card-text">{{ comment.comment_text }}</p>
            <a href="{% url 'main:detail' comment.question.id %}" class="btn btn-secondary">Retornar à enquete</a>
            <a href="{% url 'main:index' %}" class="btn btn-primary">Retornar à página inicial</a>
        </div>
    </div>
</div> {% endblock %}

enquete/main/templates/main/detail.html
{% extends 'main/base.html'%} {% block data_block %}

<div class="container">
    <div class="card w-100 mt-3" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ question.question_text }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ comment.pub_date }}</h6>
            {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            <form action="{% url 'main:vote' question.id %}" method="post">
                {% csrf_token %} {% for choice in question.choice_set.all %}
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label class="form-check-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                </div>
                {% endfor %}
                <input class="btn btn-primary" type="submit" value="Vote">
            </form>
        </div>
    </div>
    <ul class="list-group">
        <h5 class="list-group-item">
            Comments
        </h5>
        {% for comment in question.comment_set.all %}
        <li class="list-group-item">
            <a href="{% url 'main:comment' comment.id %}">
                    {{ comment.comment_text }}
                </a>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

enquete/main/templates/main/index.html
{% extends 'main/base.html'%} {% block data_block %} {% if latest_question_list %}
<div class="container">
    <ul class="list-group mt-3">
        <h3 class="list-group-item">Perguntas</h3>
        {% for question in latest_question_list %}
        <li class="list-group-item">
            <a href="{% url 'main:detail' question.id %}">
            {{ question.question_text }}
            </a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Nenhuma questão disponível.</p>
</div>
{% endif %} {% endblock %}

enquete/main/templates/main/results.html
{% extends 'main/base.html'%} {% block data_block %}
<div class="container">
    <div class="card w-100 mt-3" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ question.question_text }}</h5>
            <ul class="list-group">
                {% for choice in question.choice_set.all %}
                <li class="list-group-item">
                    {{ choice.choice_text }} -- {{ choice.votes }} voto {{ choice.votes|pluralize }}
                </li>
                {% endfor %}
            </ul>
            <a href="{% url 'main:detail' question.id %}" class="btn btn-secondary">Votar de novo.</a>
            <a href="{% url 'main:index' %}" class="btn btn-primary">Retornar à página inicial</a>
        </div>
    </div>
</div> {% endblock %}